'use client';
import { useEffect, useState } from 'react';
import type { HistoricalPoint, Quote } from '@/lib/types';

export function CompanyView({ ticker }: { ticker:string }) {
  const [quote,setQuote]=useState<Quote|null>(null); const [history,setHistory]=useState<HistoricalPoint[]>([]); const [loading,setLoading]=useState(true); const [range,setRange]=useState('1y');
  useEffect(()=>{setLoading(true);fetch(`/api/companies/${encodeURIComponent(ticker)}?range=${range}`).then(r=>r.json()).then(d=>{setQuote(d.quote);setHistory(d.history||[]);}).catch(()=>setQuote({symbol:ticker,provider:'Yahoo Finance',status:'unavailable'})).finally(()=>setLoading(false));},[ticker,range]);
  const latest=history.at(-1)?.local; const first=history.find(x=>x.local!=null)?.local; const perf=latest!=null&&first!=null&&first!==0?((latest-first)/first)*100:undefined;
  return <div className="page"><div className="breadcrumb">Companies <span>/</span> {ticker}</div><header className="company-header"><div><p className="eyebrow">COMPANY / {ticker}</p><h1>{ticker}</h1><p>Provider-backed market data. Company metadata is shown only when available.</p></div><span className={`status-pill ${quote?.status==='unavailable'?'status-muted':''}`}>{quote?.status ?? 'loading'}</span></header><section className="metric-grid"><Metric label="Price" value={quote?.price!=null?`${quote.price.toLocaleString()} ${quote.currency??''}`:'—'} /><Metric label="Change" value={quote?.previousClose!=null&&quote.price!=null?`${(quote.price-quote.previousClose).toFixed(2)} (${((quote.price/quote.previousClose-1)*100).toFixed(2)}%)`:'—'} /><Metric label="Historical performance" value={perf!=null?`${perf.toFixed(2)}%`:'—'} /><Metric label="Last observation" value={quote?.timestamp?new Date(quote.timestamp).toLocaleString():'—'} /></section><section className="chart-panel"><div className="section-head"><div><p className="eyebrow">HISTORICAL PRICE</p><h2>{loading?'Loading…':history.length?`${history.length} observations`:'Unavailable'}</h2></div><div className="range-tabs">{['1m','3m','1y','3y','5y','max'].map(r=><button key={r} className={range===r?'selected':''} onClick={()=>setRange(r)}>{r.toUpperCase()}</button>)}</div></div><div className="chart"><div className="chart-line">{history.length>1&&history.map((p,i)=><span key={p.date+i} title={`${p.date}: ${p.local??'—'}`} style={{left:`${(i/(history.length-1))*100}%`,bottom:`${p.local!=null?Math.max(4,Math.min(92,((p.local-(first??p.local))/Math.max(1,(latest??p.local)-(first??p.local)))*70+10)):5}%`}} />)}</div>{!history.length&&!loading&&<div className="chart-empty">Historical data unavailable from the configured provider.</div>}</div><div className="source-note">Source: Yahoo Finance · Values may be delayed. No unavailable financial values are estimated.</div></section></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
